name: booking_clinics
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  intl:
  table_calendar:
  cupertino_icons: ^1.0.8
  sizer:
  dio: ^5.6.0
  uuid: ^4.5.0
  dartz: ^0.10.1
  get_it: ^7.7.0
  location: ^7.0.0
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  firebase_core: ^3.3.0
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.9.0
  flutter_native_splash: ^2.4.1
  flutter_polyline_points: ^2.1.0
  iconsax: ^0.0.8

flutter_native_splash:
  background_image: "assets/images/splash_logo.png"
  android_12:
    background_image_android: "assets/images/splash_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter_Light
      fonts:
        - asset: assets/fonts/Inter_24_SemiBold.ttf
        - asset: assets/fonts/Inter_18_Bold.ttf
        - asset: assets/fonts/Inter_18_Medium.ttf
        - asset: assets/fonts/Inter_18_light.ttf
    # - family: Inter_Medium
    #   fonts:
    # - family: Inter_Bold
    #   fonts:
    # - family: Inter_Semi
      # fonts:
